
from datetime import datetime as dt
from datetime import timedelta as td

rick_id = 'jw1sf4wjmtwl'

users_rows = [
  {'id': rick_id,
   'user_name':' lihsing-lung',
   'full_name': 'Li-Hsing Lung',
   'email'    : 'ricky@rick.com',
   'salt_password': 'pw',
   'photo_link': 'https://media.licdn.com/dms/image/C4E03AQFZuKnltRJvLw/profile-displayphoto-shrink_200_200/0?e=1575504000&v=beta&t=emev1QeLoHJMtRaJAijqS1VKIhcBC0QlUptC0Ks6psM',
   'summary': '''Hey, my name is Li-Hsing Lung. I love building products and doing impactful work.

      Below are some of my views on team culture and how I've found myself to be most productive on a team. I hope we're a good match for working together!'''
   }
]

comment_rows  = []
question_rows= [{'id': 'izy4w0llxjak',
  'author_id': rick_id,
  'title': 'What is your preferred method of documenting code?',
  'description': '',
  'tags': ['coordination'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'hvf2199o9hrb',
  'author_id': rick_id,
  'title': 'How often do you read about new technologies and paradigms?',
  'description': 'What is your process for determining when to incorporate new tech into production?\n'
                 'How do you try to get a more balanced & complete understanding of the systems/tools you are investigating?',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'utx9g357klbf',
  'author_id': rick_id,
  'title': 'How do you like to handle technical debt?',
  'description': 'How do you keep yourself productive?',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'vsok5dd8p8f7',
  'author_id': rick_id,
  'title': 'What is your favorite programming language?',
  'description': 'Pick your favorite language, explain why you love it!',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '7sdzrx3p6v9a',
  'author_id': rick_id,
  'title': 'How important is consistent code style to you?',
  'description': 'Would you invest in linting tools? Would you block code merges because of style '
                 'issues?',
  'tags': ['coordination'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'jebznj1hqaos',
  'author_id': rick_id,
  'title': "Take some time to read up on Kotlin's built in nullabilty operators, !! and ?.",
  'description': 'When should you use !! and ?. Give some interesting edge cases',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'tgs85c72i4vo',
  'title': 'Would you rather have not enough meetings or too much meetings ?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'q2viob6isxw4',
  'title': 'What makes a good manager?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'j74x3ldljnf9',
  'title': 'What makes a good teammate?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'fw7moo4ead8j',
  'title': 'How do you handle heated work arguments? ',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '[ricky] https://drive.google.com/open?id=1IoUmgeyv91zdlp2EUwqHJD9-H8Pacg_K',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'pg4tk3l9ispl',
  'title': 'Do you prefer to do a daily standup meeting?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1vOOPqJvWGAtJ7dTw7hv8_Q6Dnp39WMBD',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 's9wewwhh19v0',
  'title': 'Do you prefer to talk out loud or to message your teammates?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=12ng21t9NQdgkgGTOoLlCV_Zy527tTmny',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'u8gmex7sehxb',
  'title': 'How do you prefer receiving feedback?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'lkx4j65pyc69',
  'title': 'In what ways are you easy to work with? In what ways are you not?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '[dupes] https://drive.google.com/open?id=15-U2Wyz3sLQkXZD-WC-3FQvRIscIsGV8',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'z74xfajfrs9w',
  'title': 'What are the +/- of work-from-home',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'gyfcsrid8lkv',
  'title': 'Should offices allow dogs?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '59tc3q3eck61',
  'title': "Talk us through intresting points of a 'post moterm'. What were mistakes you made, "
           'others made?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'or2x22jws5wk',
  'title': 'What do you like about the agile process? What do you not like about it?',
  'tags': ['Team Coordination'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'xjfyaaoztt4m',
  'title': 'Give me a 5 min lesson on an algorithm of your choice',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1O-Z0SYqX1Jl7OndnAbKGVpikLTWhDzfg',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'ajqgjmnjil0v',
  'title': 'What’s one of your favorite third party libraries and why?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'mxk0h25srck8',
  'title': 'What is your preferred method of testing? ',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '3cu8v8zulkhf',
  'title': 'Give me a 5 min lesson [as a cs-grad] on an interesting system.',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'kurg8igvru9p',
  'title': 'How often do you try new code editors? What makes you jump ship?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1SMbeauANXS3aaORnMnR7cKlQnDWnMuJX',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'mwl6lhsn2cco',
  'title': 'What are key differences between client and backend programming?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'ck7oqn692sog',
  'title': 'Show us a Pet project, walk through interesting parts, talk about trade offs',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'mlomxbl2p9qj',
  'title': 'When designing a new system, do you tend to design it from first principles or follow '
           'existing paradigms?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'axo2v59mrl03',
  'title': 'How much do you think the tech stack affects the success of a product',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1KUTq25mcJUCY8VA53MRG59FN_tX2FQlA',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'p31bj44u2onh',
  'title': 'Talk about a time you replaced a foundational technology',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[dupes] https://drive.google.com/open?id=1WyOSgF3Rm1xnye1PsZmv4dqlWM8nxpyH',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '2ng176y6g9zy',
  'title': "Tell us about a build/buy decision you've made / experienced",
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'rfhugxyaeivn',
  'title': 'Overall when do you think strong typing in languages are worth it?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'iaj42x2x2dot',
  'title': 'Do you think dropbox will regret moving off s3?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'zaf3asm17825',
  'title': 'Which cloud providers would you suggest?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1Wwng3Zr1mS1y8vZ6jjUbC26vDcse_t81',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '3o344nbeikr7',
  'title': 'Talk about NoSQL vs SQL, use cases & your prefences',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'liuamghd96vx',
  'title': 'Coding with Spagetti (thats working), when do you clean up?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '94hqp89qz3e7',
  'title': 'Talk about UI frameworks, the various considerations ',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'qis20pxonxm0',
  'title': 'How do you approach understanding new codebases?',
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '2kd9toyk9ukf',
  'title': "How do you feel about working with 'Old' Tech, when should a company move off?",
  'tags': ['SWE - Technical'],
  'author_id': rick_id,
  'description': '[tito] https://drive.google.com/open?id=1-loqPdEbCJF274r4Hraj-1UJjTcPT_lY',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '7q854zlky82m',
  'title': 'What value does a PM/TPM add?',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'bqgb3bmxf5t1',
  'title': 'Do you enjoy Pair Programming?',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'o6qoyyip142y',
  'title': 'What do you think a good pull request review process looks like?',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'n5mfmgw7qdau',
  'title': 'How do you perform code reviews? ',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '5f8znbjse31f',
  'title': 'Do commit messages matter? Should there be length requirements?',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'ejyy3mcykq9a',
  'title': 'What’s a good way to document all the APIs across multiple services?',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'sw3aps5iuj2y',
  'title': 'Give the +/- of leetcode/hackerrank style questions while evaluating new candidates',
  'tags': ['SWE - Team Process'],
  'author_id': rick_id,
  'description': '[dupes] https://drive.google.com/open?id=1g2_OxNwx0WGITiomDsPONvMFbiJiQZ9P',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'qf1fhefg0cpb',
  'title': 'What amount of positive reinforcement is best for you? ',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'cevx16lm2fwc',
  'title': 'How often would you like to hang out with coworkers after hours?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'kf7bdlzsvxqp',
  'title': 'Talk about work life Balance',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'b7hqvaqxecdd',
  'title': ' What do you do when you find yourself feeling unproductive?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '[ricky] https://drive.google.com/open?id=1DjYpr6qAgFo3TrvX3u_S8qMZmBiYFsPG',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'es30po6jjq5h',
  'title': 'This last year, whats a life change you’ve made that has had a large impact on your '
           'life?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'dqtf2rj73vye',
  'title': "What software 'meta' problems are most interesting to you?",
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'o1zxdfh4hvj0',
  'title': 'If you had 10 million dollars, would you retire?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'jqperxu52vxx',
  'title': 'Do you imagine yourself coding for the rest of your life, or moving onto something '
           'else?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'tmf88qxi5jfu',
  'title': 'Wha’ts your biggest regret from college?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '48c4p7cnsi47',
  'title': 'Do you prefer vacations in cities, or in natural places?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'g32xj3uqbg78',
  'title': "What's the right balance of direction vs automony for you? ",
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'iwj8tnqt5vd6',
  'title': 'Did you prefer theoretical classes or coding classes? ',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '[dupes] https://drive.google.com/open?id=1SEPr9uPNDFxLdD3dIse80mmszu2-j0MS',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'uocg3wjvs9un',
  'title': 'What is a personal trait you are trying to improve? Why, how, etc',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'r3nt3w3zvx6v',
  'title': "What is a falling out you've had in a relationship? What were mistakes you made, the "
           'other? ',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'bbw3tnt5dhfi',
  'title': 'What are pet pieves you have?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '0qw6ax3hfnm4',
  'title': 'What are some personal traits you pride yourself on? why etc',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'unq8qdxvj1ik',
  'title': 'What are ways teams can create more inclusive environments?',
  'tags': ['Personal Motivations'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'hnn5m2wye2ax',
  'title': 'What was your favorite single lesson in a class?',
  'tags': ['Misc - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '31md3osvulja',
  'title': 'Talk about a software product you currently use, whats good, what can be improved?',
  'tags': ['Misc - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'zi3s68i441dn',
  'title': 'Explain to me the rules of a board game you like.',
  'tags': ['Misc - Technical'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '9c75xx14dxks',
  'title': 'Are you a grammar nazi, or an illterate pleb?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 's5ql17d61lj2',
  'title': 'How often did you use sparknotes and barely read the book?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'nzgwinqsquvi',
  'title': 'Tell me about your favorite movie or book',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'gj1vytoxsfbl',
  'title': 'What do you think about elon musk?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '1jbzqdwc3efd',
  'title': 'What is the nicest logo you’ve ever seen.',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '2x8p603zmdzf',
  'title': 'What do you think of ubi?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'r1v8mqsfml44',
  'title': 'Who is your favorite historical figure ?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'pm59zupgen87',
  'title': 'If you were making a new high school what would be the required books?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'gkuez6lubxd4',
  'title': 'Was the facebook fine warranted?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'ryt5c0n45wyt',
  'title': 'Do you invest in individual stocks, what are some companies you are long on, short on?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': '14qftusd0m8g',
  'title': 'What are some long term effective ways to help reduce the homeless population?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'vuqxt54ivwga',
  'title': 'Should reddit be more or less aggressive with its moderation?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'lhgb8ss28isk',
  'title': 'How can political divisiveness be realistically addressed? Should it be?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 'h22g5iqsg8ul',
  'title': 'Do you think the electoral college should be removed?',
  'tags': ['Misc'],
  'author_id': rick_id,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0}]

vote_rows = []