
from datetime import datetime as dt
from datetime import timedelta as td

users_rows = [
  {'id': 0,
   'user_name':' lihsing-lung',
   'full_name': 'Li-Hsing Lung',
   'email'    : 'ricky@rick.com',
   'salt_password': 'pw',
   'photo_link':       'https://media.licdn.com/dms/image/C4E03AQFZuKnltRJvLw/profile-displayphoto-shrink_200_200/0?e=1575504000&v=beta&t=emev1QeLoHJMtRaJAijqS1VKIhcBC0QlUptC0Ks6psM',
   'summary': '''Hey, my name is Li-Hsing Lung. I love building products and doing impactful work.

      Below are some of my views on team culture and how I've found myself to be most productive on a team. I hope we're a good match for working together!'''
   },
   {'id': 1,
    'user_name': 'michael-duplessis',
    'full_name': 'Michael Duplessis',
    'email'    : 'dupes@dupes.com',
    'salt_password': 'pw',
    'photo_link': 'https://lh3.googleusercontent.com/a-/AAuE7mCLZpb1dbmKdKDOmoto2-05ezGG7i4pNnO3p4M=s384-cc',
    'summary': ''},
  {'id': 2,
   'user_name': 'tito-mbagwu',
   'full_name': 'Tito Mbagwu',
    'email'    : 'tito@tito.com',
    'salt_password': 'pw',
   'photo_link': '',
   'summary': ''},
  {'id': 3,
   'user_name': 'CoverStory',
   'full_name': 'CoverStory',
   'email'    : 'cover@story.com',
    'salt_password': 'pw',
   'photo_link': '',
   'summary': ''},
]

comment_rows  = [ 
    {'id'         : 0,  
     'question_id': 0,
     'content'    : 'comments are fucing dumb, read teh codez',    
     'type'       : 'meta',
     'author_id'  : 0,
     'parent_id'  : 0,   
     'created_at' : dt.utcnow(), 
     'up_vote'    : 69,     
     'down_vote'  : 1},
         { 'id'         : 1,  
          'question_id': 0,
          'content'    : 'is all decurem lost in this world???',    
          'type'       : 'meta',
          'author_id'  : 1,
          'parent_id'  : 0,   
          'created_at' : dt.utcnow() + td(seconds=500),
          'up_vote'    : 2,    
          'down_vote'  : 800},
             { 'id'         : 2,  
              'question_id': 0,
              'content'    : 'bitch stfu, get rich or dy tryin',    
              'type'       : 'meta',
              'author_id'  : 2,
              'parent_id'  : 1,   
              'created_at' : dt.utcnow() + td(seconds=600),
              'up_vote'    : 0 ,   
              'down_vote'  : 1},
   {'id'         : 3,  
     'question_id': 0,
     'content'    : 'i luv comments, but they dont luv me. anyone know any hot singles in the area?',    
     'type'       : 'meta',
     'author_id'  : 2,
     'parent_id'  : 3,   
     'created_at' : dt.utcnow()+td(seconds=100), 
     'up_vote'    : 2 ,    
     'down_vote'  : 50},
]

question_rows = [
 {'id': 0,
  'author_id': 0,
  'title': 'What is your preferred method of documenting code?',
  'description': '',
  'tags': ['coordination'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 20,
  'down_vote': 4
 },
 {'id': 1,
  'author_id': 0,
  'title': 'How often do you read about new technologies and paradigms?',
  'description': 'What are some specific technologies you’ve read about and how production-ready do you think they are?',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 69,
  'down_vote': 420,
 },
 {'id': 2,
  'author_id': 0,
  'title': 'How do you like to handle technical debt?',
  'description': 'How do you keep yourself productive?',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 0,
  'down_vote': 1
 },
 {'id': 3,
  'author_id': 0,
  'title': 'What is your favorite programming language?',
  'description': 'Pick your favorite language, explain why you love it!',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 10,
  'down_vote': 4
 },
 {'id': 4,
   'author_id': 0,
  'title': 'How important is consistent code style to you?',
  'description': 'Would you invest in linting tools? Would you block code merges because of style issues?',
  'tags': ['coordination'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 90,
  'down_vote': 5
 },
 {'id': 5,
  'author_id': 0,
  'title': "Take some time to read up on Kotlin's built in nullabilty operators, !! and ?.",
  'description': 'When should you use !! and ?. Give some interesting edge cases',
  'tags': ['technical'],
  'response_count': 0,
  'meta_count': 0, 
  'up_vote': 30,
  'down_vote': 2
 },
 {'id': 6,
  'title': 'Would you rather have not enough meetings or too much meetings ?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 7,
  'title': 'What makes a good manager?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 8,
  'title': 'What makes a good teammate?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 9,
  'title': 'How do you handle heated work arguments? ',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '[ricky] https://drive.google.com/open?id=1IoUmgeyv91zdlp2EUwqHJD9-H8Pacg_K',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 10,
  'title': 'Do you prefer to do a daily standup meeting?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1vOOPqJvWGAtJ7dTw7hv8_Q6Dnp39WMBD',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 11,
  'title': 'Do you prefer to talk out loud or to message your teammates?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=12ng21t9NQdgkgGTOoLlCV_Zy527tTmny',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 12,
  'title': 'How do you prefer receiving feedback?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 13,
  'title': 'In what ways are you easy to work with? In what ways are you not?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '[dupes] https://drive.google.com/open?id=15-U2Wyz3sLQkXZD-WC-3FQvRIscIsGV8',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 14,
  'title': 'What are the +/- of work-from-home',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 15,
  'title': 'Should offices allow dogs?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 16,
  'title': "Talk us through intresting points of a 'post moterm'. What were mistakes you made, "
           'others made?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 17,
  'title': 'What do you like about the agile process? What do you not like about it?',
  'tags': ['Team Coordination'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},

 {'id': 20,
  'title': 'Give me a 5 min lesson on an algorithm of your choice',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1O-Z0SYqX1Jl7OndnAbKGVpikLTWhDzfg',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 21,
  'title': 'What’s one of your favorite third party libraries and why?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 22,
  'title': 'What is your preferred method of testing? ',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 23,
  'title': 'Give me a 5 min lesson [as a cs-grad] on an interesting system.',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 24,
  'title': 'How often do you try new code editors? What makes you jump ship?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1SMbeauANXS3aaORnMnR7cKlQnDWnMuJX',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 26,
  'title': 'What are key differences between client and backend programming?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 27,
  'title': 'Show us a Pet project, walk through interesting parts, talk about trade offs',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 29,
  'title': 'When designing a new system, do you tend to design it from first principles or follow '
           'existing paradigms?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 30,
  'title': 'How much do you think the tech stack affects the success of a product',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1KUTq25mcJUCY8VA53MRG59FN_tX2FQlA',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 31,
  'title': 'Talk about a time you replaced a foundational technology',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[dupes] https://drive.google.com/open?id=1WyOSgF3Rm1xnye1PsZmv4dqlWM8nxpyH',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 32,
  'title': "Tell us about a build/buy decision you've made / experienced",
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 33,
  'title': 'Overall when do you think strong typing in languages are worth it?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 34,
  'title': 'Do you think dropbox will regret moving off s3?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 35,
  'title': 'Which cloud providers would you suggest?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1Wwng3Zr1mS1y8vZ6jjUbC26vDcse_t81',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 36,
  'title': 'Talk about NoSQL vs SQL, use cases & your prefences',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 37,
  'title': 'Coding with Spagetti (thats working), when do you clean up?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 38,
  'title': 'Talk about UI frameworks, the various considerations ',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 39,
  'title': 'How do you approach understanding new codebases?',
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 40,
  'title': "How do you feel about working with 'Old' Tech, when should a company move off?",
  'tags': ['SWE - Technical'],
  'author_id': 0,
  'description': '[tito] https://drive.google.com/open?id=1-loqPdEbCJF274r4Hraj-1UJjTcPT_lY',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 41,
  'title': 'What value does a PM/TPM add?',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 44,
  'title': 'Do you enjoy Pair Programming?',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 45,
  'title': 'What do you think a good pull request review process looks like?',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 46,
  'title': 'How do you perform code reviews? ',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 47,
  'title': 'Do commit messages matter? Should there be length requirements?',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 48,
  'title': 'What’s a good way to document all the APIs across multiple services?',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 49,
  'title': 'Give the +/- of leetcode/hackerrank style questions while evaluating new candidates',
  'tags': ['SWE - Team Process'],
  'author_id': 0,
  'description': '[dupes] https://drive.google.com/open?id=1g2_OxNwx0WGITiomDsPONvMFbiJiQZ9P',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 50,
  'title': 'What amount of positive reinforcement is best for you? ',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 51,
  'title': 'How often would you like to hang out with coworkers after hours?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 52,
  'title': 'Talk about work life Balance',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 53,
  'title': ' What do you do when you find yourself feeling unproductive?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '[ricky] https://drive.google.com/open?id=1DjYpr6qAgFo3TrvX3u_S8qMZmBiYFsPG',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 54,
  'title': 'This last year, whats a life change you’ve made that has had a large impact on your '
           'life?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 55,
  'title': "What software 'meta' problems are most interesting to you?",
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 56,
  'title': 'If you had 10 million dollars, would you retire?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 57,
  'title': 'Do you imagine yourself coding for the rest of your life, or moving onto something '
           'else?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 58,
  'title': 'Wha’ts your biggest regret from college?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 59,
  'title': 'Do you prefer vacations in cities, or in natural places?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 60,
  'title': "What's the right balance of direction vs automony for you? ",
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 61,
  'title': 'Did you prefer theoretical classes or coding classes? ',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '[dupes] https://drive.google.com/open?id=1SEPr9uPNDFxLdD3dIse80mmszu2-j0MS',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 62,
  'title': 'What is a personal trait you are trying to improve? Why, how, etc',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 63,
  'title': "What is a falling out you've had in a relationship? What were mistakes you made, the "
           'other? ',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 64,
  'title': 'What are pet pieves you have?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 65,
  'title': 'What are some personal traits you pride yourself on? why etc',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 66,
  'title': 'What are ways teams can create more inclusive environments?',
  'tags': ['Personal Motivations'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 67,
  'title': 'What was your favorite single lesson in a class?',
  'tags': ['Misc - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 68,
  'title': 'Talk about a software product you currently use, whats good, what can be improved?',
  'tags': ['Misc - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 69,
  'title': 'Explain to me the rules of a board game you like.',
  'tags': ['Misc - Technical'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 70,
  'title': 'Are you a grammar nazi, or an illterate pleb?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 71,
  'title': 'How often did you use sparknotes and barely read the book?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 72,
  'title': 'Tell me about your favorite movie or book',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 73,
  'title': 'What do you think about elon musk?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 74,
  'title': 'What is the nicest logo you’ve ever seen.',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 75,
  'title': 'What do you think of ubi?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 76,
  'title': 'Who is your favorite historical figure ?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 77,
  'title': 'If you were making a new high school what would be the required books?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 78,
  'title': 'Was the facebook fine warranted?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 79,
  'title': 'Do you invest in individual stocks, what are some companies you are long on, short on?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 80,
  'title': 'What are some long term effective ways to help reduce the homeless population?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 81,
  'title': 'Should reddit be more or less aggressive with its moderation?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 82,
  'title': 'How can political divisiveness be realistically addressed? Should it be?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0},
 {'id': 84,
  'title': 'Do you think the electoral college should be removed?',
  'tags': ['Misc'],
  'author_id': 0,
  'description': '',
  'response_count': 0,
  'meta_count': 0,
  'up_vote': 0,
  'down_vote': 0}
]

vote_rows = []